workflows:
  # Android Build Workflow
  android-workflow:
    name: Android Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      android_signing:
        - meerkat_keystore
      groups:
        - google_play
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install Rust toolchain
        script: |
          echo "🔧 Installing Rust toolchain..."
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          source $HOME/.cargo/env
          rustup toolchain install stable --allow-downgrade
          rustup default stable
          rustup target add x86_64-unknown-linux-gnu || true
          rustc --version
          cargo --version
      - name: Set up keystore
        script: |
          echo $MEERKAT_KEYSTORE_FILE | base64 --decode > $CM_BUILD_DIR/app/android/app/meerkat-keystore.jks
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/app/android/local.properties"
      - name: Get Flutter packages
        script: |
          cd app
          flutter pub get
      - name: Build Android APK
        script: |
          cd app
          flutter build apk --release
      - name: Build Android App Bundle
        script: |
          cd app
          flutter build appbundle --release
    artifacts:
      - app/build/app/outputs/flutter-apk/*.apk
      - app/build/app/outputs/bundle/release/*.aab
    publishing:
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: internal
        submit_as_draft: true

  # iOS Build Workflow (Testing Mode - No Code Signing)
  ios-workflow:
    name: iOS Build (Test Mode)
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install Rust + iOS targets
        script: |
          echo "🔧 Installing Rust + iOS targets..."
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          source $HOME/.cargo/env
          rustup toolchain install stable --allow-downgrade
          rustup default stable
          rustup target add aarch64-apple-ios
          rustup target add aarch64-apple-ios-sim
          rustup target add x86_64-apple-ios
          rustc --version
          cargo --version
      - name: Get Flutter packages
        script: |
          cd app
          flutter pub get
      - name: Install CocoaPods dependencies
        script: |
          cd app/ios
          pod install
      - name: Build iOS (no code signing for testing)
        script: |
          cd app
          flutter build ios --release --no-codesign
    artifacts:
      - app/build/ios/iphoneos/*.app

  # macOS Build Workflow (Testing Mode - No Code Signing)
  macos-workflow:
    name: macOS Build (Test Mode + GitHub Release)
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      groups:
        - github_credentials  # Optional: For GitHub Release uploads
    scripts:
      - name: Install Rust toolchain for macOS
        script: |
          echo "🔧 Installing Rust for macOS..."
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          source $HOME/.cargo/env
          rustup toolchain install stable --allow-downgrade
          rustup default stable
          rustup target add x86_64-apple-darwin
          rustup target add aarch64-apple-darwin
          rustc --version
          cargo --version
      - name: Remove code signing requirements
        script: |
          cd app/macos
          echo "🔓 Removing Team ID and code signing requirements..."
          # Remove DEVELOPMENT_TEAM lines
          sed -i '' '/DEVELOPMENT_TEAM = 3W7H4PYMCV;/d' Runner.xcodeproj/project.pbxproj
          sed -i '' '/DEVELOPMENT_TEAM/d' Runner.xcodeproj/project.pbxproj
          # Change CODE_SIGN_IDENTITY to "-" (sign to run locally)
          sed -i '' 's/CODE_SIGN_IDENTITY = "Apple Development";/CODE_SIGN_IDENTITY = "-";/g' Runner.xcodeproj/project.pbxproj
          sed -i '' 's/"CODE_SIGN_IDENTITY\[sdk=macosx\*\]" = "Apple Development";/"CODE_SIGN_IDENTITY[sdk=macosx*]" = "-";/g' Runner.xcodeproj/project.pbxproj
          # Change CODE_SIGN_STYLE to Manual
          sed -i '' 's/CODE_SIGN_STYLE = Automatic;/CODE_SIGN_STYLE = Manual;/g' Runner.xcodeproj/project.pbxproj
          echo "✅ Code signing disabled successfully"
      - name: Get Flutter packages
        script: |
          cd app
          flutter pub get
      - name: Install CocoaPods dependencies
        script: |
          cd app/macos
          pod install
      - name: Build macOS application (no code signing for testing)
        script: |
          cd app
          flutter build macos --release
      - name: Package macOS app (ZIP + DMG)
        script: |
          cd app/build/macos/Build/Products/Release
          APP_NAME="Meerkat.app"
          ZIP_NAME="Meerkat-macOS.zip"
          DMG_NAME="Meerkat-macOS.dmg"
          
          echo "📦 Creating ZIP archive..."
          ditto -c -k --keepParent "$APP_NAME" "$ZIP_NAME"
          
          echo "💿 Creating DMG installer..."
          hdiutil create -volname Meerkat -srcfolder "$APP_NAME" -ov -format UDZO "$DMG_NAME"
          
          echo "✅ Packaging complete!"
          echo "📂 Contents:"
          ls -lh *.app *.zip *.dmg
      - name: Upload to GitHub Releases (Optional)
        script: |
          # Only runs if GITHUB_TOKEN is set and this is a tag build
          if [ -n "$GITHUB_TOKEN" ] && [ -n "$CM_TAG" ]; then
            echo "🚀 Uploading to GitHub Releases..."
            cd app/build/macos/Build/Products/Release
            
            # Install GitHub CLI if not present
            brew install gh || true
            
            # Create or update release
            gh release create "$CM_TAG" \
              "Meerkat-macOS.zip" \
              "Meerkat-macOS.dmg" \
              --repo "$CM_REPO_SLUG" \
              --title "Meerkat $CM_TAG" \
              --notes "macOS Build (Unsigned) - Contains .app in ZIP and .dmg installer. Right-click Open for first launch." \
              || echo "⚠️ Release upload skipped (no tag or token)"
          else
            echo "ℹ️ Skipping GitHub release (not a tag build or GITHUB_TOKEN not set)"
          fi
    artifacts:
      - app/build/macos/Build/Products/Release/Meerkat.app
      - app/build/macos/Build/Products/Release/*.zip
      - app/build/macos/Build/Products/Release/*.dmg

  # Windows Build Workflow
  windows-workflow:
    name: Windows Build
    max_build_duration: 60
    instance_type: windows_x2
    environment:
      flutter: stable
      groups:
        - windows_signing
    scripts:
      - name: Get Flutter packages
        script: |
          cd app
          flutter pub get
      - name: Build Windows executable
        script: |
          cd app
          flutter build windows --release
      - name: Create Windows installer
        script: |
          cd app
          # Build MSIX package
          flutter pub run msix:create
      - name: Build portable ZIP
        script: |
          cd app/build/windows/x64/runner/Release
          7z a -tzip Meerkat-Windows-Portable.zip *
    artifacts:
      - app/build/windows/**/*.msix
      - app/build/windows/**/*.zip
      - app/build/windows/x64/runner/Release/*.exe

  # All Platforms Build
  all-platforms-workflow:
    name: Build All Platforms
    max_build_duration: 90
    instance_type: mac_mini_m2
    triggering:
      events:
        - push
        - tag
        - pull_request
      branch_patterns:
        - pattern: 'main'
          include: true
          source: true
        - pattern: 'release/*'
          include: true
          source: true
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install Rust (for all builds)
        script: |
          echo "🔧 Installing Rust globally..."
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          source $HOME/.cargo/env
          rustup toolchain install stable --allow-downgrade
          rustup default stable
          rustup target add aarch64-apple-ios x86_64-apple-ios aarch64-apple-ios-sim x86_64-unknown-linux-gnu
          rustc --version
          cargo --version
      - name: Get Flutter packages
        script: |
          cd app
          flutter pub get
      - name: Run Flutter analyze
        script: |
          cd app
          flutter analyze
      - name: Run Flutter tests
        script: |
          cd app
          flutter test
      - name: Build Android APK
        script: |
          cd app
          flutter build apk --release
      - name: Build iOS (no code signing for test)
        script: |
          cd app
          flutter build ios --release --no-codesign
      - name: Build macOS (no code signing for test)
        script: |
          cd app
          flutter build macos --release
    artifacts:
      - app/build/app/outputs/flutter-apk/*.apk
      - app/build/ios/iphoneos/*.app
      - app/build/macos/Build/Products/Release/*.app
